<?php
return array(
    '002' => 'Africa',
    '015' => 'Northern Africa',
    '011' => 'Western Africa',
    '017' => 'Middle Africa',
    '014' => 'Eastern Africa',
    '018' => 'Southern Africa',
    '150' => 'Europe',
    '154' => 'Northern Europe',
    '155' => 'Western Europe',
    '151' => 'Eastern Europe',
    '039' => 'Southern Europe',
    '019' => 'Americas',
    '021' => 'Northern Americas',
    '029' => 'Caribbean',
    '013' => 'Central America',
    '005' => 'South America',
    '142' => 'Asia',
    '143' => 'Central Asia',
    '030' => 'Eastern Asia',
    '034' => 'Southern Asia',
    '035' => 'South-Eastern Asia',
    '145' => 'Western Asia',
    '009' => 'Oceania',
    '053' => 'Australia and New Zealand',
    '054' => 'Melanesia',
    '057' => 'Micronesia',
    '061' => 'Polynesia'
);